server:
  port: 9011
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: web
          uri: lb://web      # lb代表从注册中心获取服务
          predicates:
            - Path=/webb/**         # 转发该路径
          filters:
            - StripPrefix=1             # 带前缀
        - id: baidu
          uri: http://www.baidu.com
          pridicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
